CONNECT DB_OWNER/DB_OWNER;

DROP TABLE DB_OWNER.employees CASCADE CONSTRAINTS;
DROP TABLE DB_OWNER.hr_reviews CASCADE CONSTRAINTS;
DROP TABLE DB_OWNER.reports CASCADE CONSTRAINTS;
DROP TABLE DB_OWNER.countries CASCADE CONSTRAINTS;
DROP TABLE DB_OWNER.locations CASCADE CONSTRAINTS;
DROP TABLE DB_OWNER.corporation_groups CASCADE CONSTRAINTS;
